### ISSUE TITLE
Mapper 관련 예외 발생(해결)

### ISSUE THREAD

**Issue by soeunl** [heyejiyang/PokemonBook_pj#7]
![image](https://github.com/heyejiyang/PokemonBook_pj/assets/154653812/fa75c5fd-30a2-4b9d-9291-6cc781a770df)
![image](https://github.com/heyejiyang/PokemonBook_pj/assets/154653812/1c7b7b1c-e53a-40cb-9c90-2516c2535ebe)
웹페이지 실행과 동작은 문제 없이 되지만, 웹페이지를 실행할 때 콘솔창에 예외 문구가 계속 뜨는 문제가 발생하였습니다.
BeanContainer와 DispatcherServlet에서 발생한 예외라 추측하고 두 곳의 코드를 계속 수정하였으나, 예외가 처리되지 않았고 강사님께 도움을 요청하였습니다.
![image](https://github.com/heyejiyang/PokemonBook_pj/assets/154653812/87dabbfd-caf3-41fb-ba51-73c71720fb2b)
원인은 master 브랜치에서 작업본을 받아오는 과정에서  PokemonMapper.xml이 생성되었고,  MapperProvider와 mybatis-config에 새로 생긴 Mapper의 경로를 설정하지 않았기 때문이었습니다.
![image](https://github.com/heyejiyang/PokemonBook_pj/assets/154653812/91984662-a00e-4e46-bdc6-0396ff2dd7d3)
![image](https://github.com/heyejiyang/PokemonBook_pj/assets/154653812/23a4901c-f2cd-4f69-b220-607baeb5c581)
경로를 설정하자 예외 문구가 뜨지 않고 정상 처리되었습니다.

**Comment by heyejiyang** [comment]
덕분에 해결했습니다😀
